name: Auto Release Workflow

on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
        contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create Release and Upload Artifact
        uses: softprops/action-gh-release@v2
        with:
            files: dist/index.js
